### ISSUE TITLE
Disable logic (ex. for buttons)

### ISSUE THREAD

**Issue by Max93** [lovethesign/jeffrey#103]
We must use [disabled](https://developer.mozilla.org/en-US/docs/Web/CSS/%3adisabled) attribute inside components like :

```html
<button class="some-class" disabled>
some text
</button>
```

```css
some-class:disabled {
  background: #ccc;
}
```
